---
- name: LVM 작업
  hosts: webservers
  gather_facts: true
  tasks:
    ########################################################
    # 에러메세지 작업:
    # * sdb 디스크가 없으면 => 'Ther device does not exist'
    # * 파티션이 800MiB보다 작으면 => 'Size not Enough'
    # * LVM 작업
    # * 파티션 작업
    # * LVM 작업
    #   - VG 작업
    #   - LV 작업
    # * 파일시스템 작업
    # * 마운트 작업(/etc/fstab)
    ########################################################
    - name: 파티션 작업
      community.general.parted:
        # parted /dev/sdb/mkpart/primary 1MiB 100%
        # poarted /dev/sdb set 1 lvm on
        device: /dev/sdb
        number: 1
        part_start: 1MiB
        part_end: 100%
        flags: [ lvm ]
        state: present

    - name: 팩트 재 수집
      ansible.builtin.setup:
        gather_subnet:
          - facter

    - name: 에러 메세지 출력 - 파티션 크기 점검
      ansible.builtin.fail:
        msg: 'Size not Enough'
      vars:
        sdb1size: "{{ (ansible_devices.sdb.partitions.sdb1.size | split)[0] }}"
      when: sdb1size | float < 800

    - name: LVM 작업 - research VG
      community.general.lvg:
        # vgcreate vg1 /dev/sdb1
        vg: research
        pvs: /dev/sdb1

    - name: LVM 작업 - data LVM
      community.general.lvol:
        # lvcreate -L 500m -n data research
        vg: research
        lv: data
        size: 500m

    - name: FS 작업 - ext4
      community.general.filesystem:
        # mkfs -t ext4 /dev/research/data
        fstype: ext4
        dev: /dev/sdb1
        force: true

    - name: Mount 작업 - /mnt/research
      ansible.posix.mount:
        # mount -t ext4 -o defaults /dev/research/data /mnt/research
        # vi /etc/fstab
        # => /dev/research/data /mnt/research ext4  defaults 0 2
        src: /dev/research/data
        path: /mnt/research
        fstype: ext4
        opts: defaults
        state: mounted
