---
- name: 0) 시간 동기화 복원
  hosts: all
  tasks:
    - name: 1) 타임 존 설정
      # Asia/Seoul => 변수(host_timezone)
      ansible.builtin.timezone:
        name: "{{ host_timezone }}"
      vars:
        host_timezone: "Asia/Seoul"

    - name: 2) NTP 서버에 시간 동기화
      # kr.pool.ntp.org
      ansible.builtin.import_role:
        name: rhel-system-roles.timesync
      vars:
        timesyn_ntp_servers:
          - hostname: kr.pool.ntp.org
            iburst: true
