---
- name: 0) Restore
  hosts: webservers
  gather_facts: true
  vars_files:
    - vars/vars.yml
  tasks:
    - name: 1) 방화벽 포트 제거
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: disabled
      loop: "{{ firewall_rule }}"

    - name: 2) 서비스 중지 - {{ services }}
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: false
        state: stopped
      loop: "{{ services }}"

    - name: 3) 웹 서비스 설정 삭제
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    - name: 4) 패키지 삭제 - {{ packages }}
      ansible.builtin.dnf:
        name:
          - mod_ssl
          - httpd
        state: absent
