---
- name: Play 01) EPEL 패키지 설치
  hosts: all
  gather_facts: false
  tasks:
    - name: 1) epel-release 패키지 설치
      ansible.builtin.include_tasks: install_package.yml
      vars:
        package:
          web_pkg: epel-release
    - name: 2) boxes 패키지 설치
     # boxes 패키지는 반드시 epel-release 패키지 설치 이후에 설치해야 한다.
      ansible.builtin.include_tasks: install_package.yml
      vars:
        package:
          web_pkg: boxes
