---
- name: Task Failure Exercise
  hosts: databases
  vars:
    web_package: httpd
    db_package: mariadb-server
    db_service: mariadb
  tasks:
    - name: Start {{ db_service }} service
      service:
        name: "{{ db_service }}"
        state: stopped
        enabled: false

    - name: Install {{ web_package }} package
      ansible.builtin.yum:
        name: "{{ web_package }}"
        state: absent


    - name: Install {{ db_package }} package
      ansible.builtin.yum:
        name: "{{ db_package }}"
        state: absent
