---
- name: Restore user-vhost-role.yml
  hosts: all
  tasks:
    - name: Role Test
      ansible.builtin.include_role:
        name: rollbacksvc
      vars:
        web_files:
          - /var/www/html/index.html

