---
- name: 0) 사용자 생성
  hosts: devservers
  remote_user: devops
  become: true
  vars_files:
    - vars/secret.yml
  tasks:
    - name: 1) 시크릿 파일을 이용한 사용자 추가
      user:
        name: "{{  item.name }}"
        password: "{{ item.pw | password_hash('sha512') }}"
      with_items: "{{ newusers }}"
